### ISSUE TITLE
Dan's Assignment 1 

### ISSUE THREAD

**Issue by DD-Scott** [uxvictor/MiniProject1#1]
I'm going to pull the presidential speeches and do a text analysis of various presidents.

https://github.com/DD-Scott/MiniProject1

https://millercenter.org/the-presidency/presidential-speeches/december-7-1796-eighth-annual-message-congress

**Comment by uxvictor** [comment]
Sounds reasonable.  Good luck with the prez speech analysis

**Comment by uxvictor** [comment]
Dan's mini project looks good. Closing issue
