### ISSUE TITLE
working on data still?

### ISSUE THREAD

**Issue by DD-Scott** [uxvictor/MiniProject1#2]
@uxvictor 
Hi Victor, what do you make of the 'binomial' analysis for extra credit?

**Comment by uxvictor** [comment]
Have not got there yet.  Am working on homework now.

**Comment by DD-Scott** [comment]
It's looking a lot better.  You did repeat the Assignment 1 instructions again at the bottom of the notebook. @uxvictor

**Comment by uxvictor** [comment]
It is not really a repeat.  There are responses (answers to the questions) there.

**Comment by DD-Scott** [comment]
Try swapping/moving the split to be after the 'clean function'  Also, add some characters to your clean function to remove '-'.

```
# remove periods, commas, etc stuck to the edges of words
for i in range(len(wds)):
    wds [i] = cleanWord (wds [i])

# split string into an array of words using any sequence of spaces "\s+" 
wds = re.split('\s+',t)  
```

**Comment by DD-Scott** [comment]
Also, because of the pre-processing (pdf-->text) there are a lot of '\n\n' in the HTML text.  You might could do a find/replace (re.sub) for all the dashes followed by \n and just remove those \n

![image](https://user-images.githubusercontent.com/111726008/189780108-f1d5abe8-bc27-462e-a772-4a67ba4fb724.png)

That way, you get the whole word and not two {harmoniz, ing}

**Comment by DD-Scott** [comment]
so the order to do that would be to remove the -\n first, then change all \n to ' ' (one space).  Cleans it right up.

**Comment by uxvictor** [comment]
The split is after the cleanHTML.

**Comment by uxvictor** [comment]
Also, for the first text file, there are only 194 of the unprintable words.  There are 1127 lines in the text file.  So it being related to any carriange return/line feed doesn't match the results.   What is in the file only 194 times that is not printable is one of my questions

**Comment by uxvictor** [comment]
Ah, I think you mean the cleanWord.  I have that after the split. Got it.  Looking at it

**Comment by DD-Scott** [comment]
`
def cleanWord (w):
     # r in r'[.,"\']' tells to treat \ as a regular character 
     # but we need to escape ' with \'
     # any character between the brackets [] is to be removed 
     z = re.sub(r'http\S+', ' ', w)    #remove URLs
     z1 = re.sub('[\n\n|\n]',' ',z)     #get rid of line returns chr(10) chr(13)
     z2 = re.sub('-\n]','',z1)   #fix the hyphenated words at end of lines
     z3 = re.sub('[\]\[~,"\.\'`&\|:@>*;/=\n\r)(-]', '', z2)  #remove other symbols
     z4 = re.sub('et al', ' ', z3)  #remove this et al (and others)
     #z5 = re.sub('\s+.',' ',z4)   #not really needed
     y = re.sub('[0-9]+', "", z4)  # get rid of numbers
    return y
`

**Comment by uxvictor** [comment]
Thanks for the help.  Looking much better now
